export const MIDIPercussion = {
  35: 'synth_drum',
  36: 'synth_drum',
  37: 'taiko_drum',
  38: 'synth_drum',
  39: 'applause', //Hand Clap,
  40: 'taiko_drum', //Snare Drum 2,
  41: 'melodic_tom', //Low Tom 2,
  42: 'synth_drum', //Closed Hi-hat,
  43: 'melodic_tom', //Low Tom 1,
  44: 'synth_drum', //Pedal Hi-hat,
  45: 'melodic_tom', //Mid Tom 2,
  46: 'synth_drum', //Open Hi-hat,
  47: 'melodic_tom', //Mid Tom 1,
  48: 'melodic_tom', //High Tom 2,
  49: 'reverse_cymbal', //Crash Cymbal 1,
  50: 'melodic_tom', //High Tom 1,
  51: 'reverse_cymbal', //Ride Cymbal 1,
  52: 'reverse_cymbal', //Chinese Cymbal,
  53: 'tubular_bells', //Ride Bell,
  54: 'synth_bass_2', //Tambourine,
  55: 'reverse_cymbal', //Splash Cymbal,
  56: 'tinkle_bell', //Cowbell,
  57: 'reverse_cymbal', //Crash Cymbal 2,
  58: 'synth_drum', //Vibra Slap,
  59: 'reverse_cymbal', //Ride Cymbal 2,
  60: 'synth_drum', //High Bongo,
  61: 'synth_drum', //Low Bongo,
  62: 'kalimba', //Mute High Conga,
  63: 'kalimba', //Open High Conga,
  64: 'kalimba', //Low Conga,
  65: 'bag_pipe', //High Timbale,
  66: 'bag_pipe', //Low Timbale,
  67: 'synth_drum', //High Agogô,
  68: 'synth_drum', //Low Agogô,
  69: 'synth_drum', //Cabasa,
  70: 'synth_drum', //Maracas,
  71: 'whistle', //Short Whistle,
  72: 'whistle', //Long Whistle,
  73: 'vibraphone', //Short Güiro,
  74: 'vibraphone', //Long Güiro,
  75: 'vibraphone', //Claves,
  76: 'woodblock', //High Wood Block,
  77: 'woodblock', //Low Wood Block,
  78: 'xylophone', //Mute Cuíca,
  79: 'xylophone', //Open Cuíca,
  80: 'steel_drums', //Mute Triangle,
  81: 'steel_drums', //Open Triangle
};
